version: '3.8'

services:
  engine-recommender-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: engine-recommender-api
    #network_mode: host
    ports:
      - "5000:5000"
    restart: unless-stopped
    environment:
      - API_KEY_SEARCH_CUSTOM_ENGINE=AIzaSyAIEUUHD4lTAYMqhr1MnC9UoEtcZC3Ula4
      - CX_SEARCH_CUSTOM_ENGINE=222cc59320c3a4cde
    command: ["python", "mode_semantic.py"]
